services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./backend:/app

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 5173:5173
    volumes:
      - /app/node_modules
      - ./frontend:/app
  db:
    container_name: db
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
